// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MindSite.Data;

#nullable disable

namespace MindSite.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("MindSite.Entities.Arquivo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Caminho")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("MimeType")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("NomeOriginal")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("ServicoId")
                        .HasColumnType("int");

                    b.Property<long>("Tamanho")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UploadEm")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ServicoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Arquivos");
                });

            modelBuilder.Entity("MindSite.Entities.Avaliacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<string>("Comentario")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<DateTime>("CriadaEm")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Estrelas")
                        .HasColumnType("int");

                    b.Property<int>("FornecedorId")
                        .HasColumnType("int");

                    b.Property<int>("ServicoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("FornecedorId");

                    b.HasIndex("ServicoId")
                        .IsUnique();

                    b.ToTable("Avaliacoes");
                });

            modelBuilder.Entity("MindSite.Entities.AvaliacaoSistema", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comentario")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<DateTime>("CriadaEm")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Estrelas")
                        .HasColumnType("int");

                    b.Property<int>("ServicoId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("ServicoId", "UsuarioId")
                        .IsUnique();

                    b.ToTable("AvaliacoesSistema");
                });

            modelBuilder.Entity("MindSite.Entities.EmpresaInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CNPJ")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Cidade")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("EmailEmpresa")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Estado")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("NomeEmpresa")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("SobreVoce")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("TelefoneEmpresa")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("EmpresaInfo");
                });

            modelBuilder.Entity("MindSite.Entities.ItemPortfolio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descricao")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<int>("FornecedorId")
                        .HasColumnType("int");

                    b.Property<string>("ImagemCaminho")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("LinkUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("FornecedorId");

                    b.ToTable("Portfolios");
                });

            modelBuilder.Entity("MindSite.Entities.LogAcao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("RealizadaEm")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("MindSite.Entities.Mensagem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApagarParaMim")
                        .HasColumnType("longtext");

                    b.Property<bool>("ApagarParaTodos")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("varchar(8000)");

                    b.Property<int>("DestinatarioId")
                        .HasColumnType("int");

                    b.Property<bool>("Editada")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("EditadaEm")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("EnviadaEm")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Lida")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("RemetenteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DestinatarioId");

                    b.HasIndex("RemetenteId");

                    b.ToTable("Mensagens");
                });

            modelBuilder.Entity("MindSite.Entities.MensagemGrupo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApagarParaMim")
                        .HasColumnType("longtext");

                    b.Property<bool>("ApagarParaTodos")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("varchar(8000)");

                    b.Property<bool>("Editada")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("EditadaEm")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("EhSistema")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("EnviadaEm")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("RemetenteId")
                        .HasColumnType("int");

                    b.Property<int>("ThreadUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RemetenteId");

                    b.HasIndex("ThreadUserId");

                    b.ToTable("MensagensGrupo");
                });

            modelBuilder.Entity("MindSite.Entities.Notificacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Contador")
                        .HasColumnType("int");

                    b.Property<string>("Corpo")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<DateTime>("CriadaEm")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Lida")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("ServicoId")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Url")
                        .HasColumnType("longtext");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Notificacoes");
                });

            modelBuilder.Entity("MindSite.Entities.Proposta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CriadaEm")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataEntrega")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("FechadaPeloAdmin")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("FornecedorId")
                        .HasColumnType("int");

                    b.Property<string>("Mensagem")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<int>("ServicoId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("FornecedorId");

                    b.HasIndex("ServicoId");

                    b.ToTable("Propostas");
                });

            modelBuilder.Entity("MindSite.Entities.Servico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataEntrega")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataPrazoCliente")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("FornecedorId")
                        .HasColumnType("int");

                    b.Property<string>("NomeProjeto")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<decimal?>("OrcamentoCliente")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime?>("PagamentoFinalEm")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("PagamentoFinalFeito")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("PagamentoInicialEm")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("PagamentoInicialFeito")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("PrazoCliente")
                        .HasColumnType("int");

                    b.Property<bool>("RepasseEfetuado")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Requisitos")
                        .HasMaxLength(8000)
                        .HasColumnType("varchar(8000)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("StripePaymentIntentIdFinal")
                        .HasColumnType("longtext");

                    b.Property<string>("StripePaymentIntentIdInicial")
                        .HasColumnType("longtext");

                    b.Property<string>("StripeSessionIdFinal")
                        .HasColumnType("longtext");

                    b.Property<string>("StripeSessionIdInicial")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("TaxaPlataforma")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<decimal?>("Valor")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("ValorAdicional")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("ValorRepasseFornecedor")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("FornecedorId");

                    b.ToTable("Servicos");
                });

            modelBuilder.Entity("MindSite.Entities.SolicitacaoMudanca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aceita")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CriadaEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("varchar(8000)");

                    b.Property<bool>("Recusada")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("RespostaFornecedor")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<int>("ServicoId")
                        .HasColumnType("int");

                    b.Property<int>("SolicitanteId")
                        .HasColumnType("int");

                    b.Property<decimal?>("ValorAdicional")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("ServicoId");

                    b.HasIndex("SolicitanteId");

                    b.ToTable("SolicitacoesMudanca");
                });

            modelBuilder.Entity("MindSite.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AceitouContratoClienteEm")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("AceitouContratoFornecedorEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CPF")
                        .HasMaxLength(14)
                        .HasColumnType("varchar(14)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Endereco")
                        .HasColumnType("longtext");

                    b.Property<string>("FotoPerfilUrl")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LinkedInUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<bool>("NotificacoesChat")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("NotificacoesEmail")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SobreVoce")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("TokenResetExpira")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TokenResetSenha")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UltimoAcesso")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("WhatsAppNumero")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "josuegumer364@gmail.com",
                            IsOnline = false,
                            NomeCompleto = "Josué Gumer",
                            NotificacoesChat = true,
                            NotificacoesEmail = true,
                            Role = 2,
                            SenhaHash = "$2a$12$UeHf1Yo1INS.J2enCd.kruqxNqtK4AAx59cFHVE5uHft2oOJtZYvS",
                            Status = 0,
                            Telefone = "(11) 96743-1518"
                        },
                        new
                        {
                            Id = 2,
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "albertoZiurk@gmail.com",
                            IsOnline = false,
                            NomeCompleto = "Alberto Ziurkelis",
                            NotificacoesChat = true,
                            NotificacoesEmail = true,
                            Role = 2,
                            SenhaHash = "$2a$12$UeHf1Yo1INS.J2enCd.kruqxNqtK4AAx59cFHVE5uHft2oOJtZYvS",
                            Status = 0,
                            Telefone = "(11) 99999-9999"
                        },
                        new
                        {
                            Id = 3,
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "neryDio@gmail.com",
                            IsOnline = false,
                            NomeCompleto = "Guilherme Beltrame",
                            NotificacoesChat = true,
                            NotificacoesEmail = true,
                            Role = 2,
                            SenhaHash = "$2a$12$UeHf1Yo1INS.J2enCd.kruqxNqtK4AAx59cFHVE5uHft2oOJtZYvS",
                            Status = 0,
                            Telefone = "(11) 88888-8888"
                        },
                        new
                        {
                            Id = 4,
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "alberto@gmail.com",
                            IsOnline = false,
                            NomeCompleto = "Alberto Cliente",
                            NotificacoesChat = true,
                            NotificacoesEmail = true,
                            Role = 0,
                            SenhaHash = "$2a$12$UeHf1Yo1INS.J2enCd.kruqxNqtK4AAx59cFHVE5uHft2oOJtZYvS",
                            Status = 0,
                            Telefone = "(11) 88888-8888"
                        },
                        new
                        {
                            Id = 5,
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "ziurkelis@gmail.com",
                            IsOnline = false,
                            NomeCompleto = "Alberto Fornecedor",
                            NotificacoesChat = true,
                            NotificacoesEmail = true,
                            Role = 1,
                            SenhaHash = "$2a$12$UeHf1Yo1INS.J2enCd.kruqxNqtK4AAx59cFHVE5uHft2oOJtZYvS",
                            Status = 0,
                            Telefone = "(11) 88888-8888"
                        },
                        new
                        {
                            Id = 6,
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "guilherme@gmail.com",
                            IsOnline = false,
                            NomeCompleto = "Guilherme Cliente",
                            NotificacoesChat = true,
                            NotificacoesEmail = true,
                            Role = 0,
                            SenhaHash = "$2a$12$UeHf1Yo1INS.J2enCd.kruqxNqtK4AAx59cFHVE5uHft2oOJtZYvS",
                            Status = 0,
                            Telefone = "(11) 88888-8888"
                        },
                        new
                        {
                            Id = 7,
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "nery@gmail.com",
                            IsOnline = false,
                            NomeCompleto = "Guilherme Fornecedor",
                            NotificacoesChat = true,
                            NotificacoesEmail = true,
                            Role = 1,
                            SenhaHash = "$2a$12$UeHf1Yo1INS.J2enCd.kruqxNqtK4AAx59cFHVE5uHft2oOJtZYvS",
                            Status = 0,
                            Telefone = "(11) 88888-8888"
                        },
                        new
                        {
                            Id = 8,
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "josue@gmail.com",
                            IsOnline = false,
                            NomeCompleto = "Josué Cliente",
                            NotificacoesChat = true,
                            NotificacoesEmail = true,
                            Role = 0,
                            SenhaHash = "$2a$12$UeHf1Yo1INS.J2enCd.kruqxNqtK4AAx59cFHVE5uHft2oOJtZYvS",
                            Status = 0,
                            Telefone = "(11) 88888-8888"
                        },
                        new
                        {
                            Id = 9,
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "gumer@gmail.com",
                            IsOnline = false,
                            NomeCompleto = "Josué Fornecedor",
                            NotificacoesChat = true,
                            NotificacoesEmail = true,
                            Role = 1,
                            SenhaHash = "$2a$12$UeHf1Yo1INS.J2enCd.kruqxNqtK4AAx59cFHVE5uHft2oOJtZYvS",
                            Status = 0,
                            Telefone = "(11) 88888-8888"
                        });
                });

            modelBuilder.Entity("MindSite.Entities.Arquivo", b =>
                {
                    b.HasOne("MindSite.Entities.Servico", "Servico")
                        .WithMany("Arquivos")
                        .HasForeignKey("ServicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MindSite.Entities.Usuario", "Usuario")
                        .WithMany("Arquivos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Servico");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("MindSite.Entities.Avaliacao", b =>
                {
                    b.HasOne("MindSite.Entities.Usuario", "Cliente")
                        .WithMany("AvaliacoesCliente")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MindSite.Entities.Usuario", "Fornecedor")
                        .WithMany("AvaliacoesFornecedor")
                        .HasForeignKey("FornecedorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MindSite.Entities.Servico", "Servico")
                        .WithOne("Avaliacao")
                        .HasForeignKey("MindSite.Entities.Avaliacao", "ServicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Fornecedor");

                    b.Navigation("Servico");
                });

            modelBuilder.Entity("MindSite.Entities.AvaliacaoSistema", b =>
                {
                    b.HasOne("MindSite.Entities.Servico", "Servico")
                        .WithMany("AvaliacoesSistema")
                        .HasForeignKey("ServicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MindSite.Entities.Usuario", "Usuario")
                        .WithMany("AvaliacoesSistema")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Servico");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("MindSite.Entities.EmpresaInfo", b =>
                {
                    b.HasOne("MindSite.Entities.Usuario", "Usuario")
                        .WithOne("Empresa")
                        .HasForeignKey("MindSite.Entities.EmpresaInfo", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("MindSite.Entities.ItemPortfolio", b =>
                {
                    b.HasOne("MindSite.Entities.Usuario", "Fornecedor")
                        .WithMany("Portfolio")
                        .HasForeignKey("FornecedorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fornecedor");
                });

            modelBuilder.Entity("MindSite.Entities.LogAcao", b =>
                {
                    b.HasOne("MindSite.Entities.Usuario", "Usuario")
                        .WithMany("Logs")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("MindSite.Entities.Mensagem", b =>
                {
                    b.HasOne("MindSite.Entities.Usuario", "Destinatario")
                        .WithMany("MensagensRecebidas")
                        .HasForeignKey("DestinatarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MindSite.Entities.Usuario", "Remetente")
                        .WithMany("MensagensEnviadas")
                        .HasForeignKey("RemetenteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Destinatario");

                    b.Navigation("Remetente");
                });

            modelBuilder.Entity("MindSite.Entities.MensagemGrupo", b =>
                {
                    b.HasOne("MindSite.Entities.Usuario", "Remetente")
                        .WithMany()
                        .HasForeignKey("RemetenteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MindSite.Entities.Usuario", "ThreadUser")
                        .WithMany()
                        .HasForeignKey("ThreadUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Remetente");

                    b.Navigation("ThreadUser");
                });

            modelBuilder.Entity("MindSite.Entities.Notificacao", b =>
                {
                    b.HasOne("MindSite.Entities.Usuario", "Usuario")
                        .WithMany("Notificacoes")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("MindSite.Entities.Proposta", b =>
                {
                    b.HasOne("MindSite.Entities.Usuario", "Fornecedor")
                        .WithMany("PropostasFeitas")
                        .HasForeignKey("FornecedorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MindSite.Entities.Servico", "Servico")
                        .WithMany("Propostas")
                        .HasForeignKey("ServicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fornecedor");

                    b.Navigation("Servico");
                });

            modelBuilder.Entity("MindSite.Entities.Servico", b =>
                {
                    b.HasOne("MindSite.Entities.Usuario", "Cliente")
                        .WithMany("ServicosCliente")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MindSite.Entities.Usuario", "Fornecedor")
                        .WithMany("ServicosFornecedor")
                        .HasForeignKey("FornecedorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Cliente");

                    b.Navigation("Fornecedor");
                });

            modelBuilder.Entity("MindSite.Entities.SolicitacaoMudanca", b =>
                {
                    b.HasOne("MindSite.Entities.Servico", "Servico")
                        .WithMany("Mudancas")
                        .HasForeignKey("ServicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MindSite.Entities.Usuario", "Solicitante")
                        .WithMany()
                        .HasForeignKey("SolicitanteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Servico");

                    b.Navigation("Solicitante");
                });

            modelBuilder.Entity("MindSite.Entities.Servico", b =>
                {
                    b.Navigation("Arquivos");

                    b.Navigation("Avaliacao");

                    b.Navigation("AvaliacoesSistema");

                    b.Navigation("Mudancas");

                    b.Navigation("Propostas");
                });

            modelBuilder.Entity("MindSite.Entities.Usuario", b =>
                {
                    b.Navigation("Arquivos");

                    b.Navigation("AvaliacoesCliente");

                    b.Navigation("AvaliacoesFornecedor");

                    b.Navigation("AvaliacoesSistema");

                    b.Navigation("Empresa");

                    b.Navigation("Logs");

                    b.Navigation("MensagensEnviadas");

                    b.Navigation("MensagensRecebidas");

                    b.Navigation("Notificacoes");

                    b.Navigation("Portfolio");

                    b.Navigation("PropostasFeitas");

                    b.Navigation("ServicosCliente");

                    b.Navigation("ServicosFornecedor");
                });
#pragma warning restore 612, 618
        }
    }
}
